Add possibility to specify cert and key name incl. ext
kereis/traefik-certs-dumper pull request #78
Opened 2022-03-16 14:07 UTC by BobSilent

Allow setting own filenames and extensions for the dumped certificates

2022-04-26 12:53 UTC, kereis requested changes
Thanks for your contribution and sorry to have you kept waiting.

I left some comments on your changes. Afterwards, we can merge your changes. 👍

2022-04-26 12:53 UTC, kereis commented on bin/dump.sh
> +privatekey_file= ${privatekey_file_name}${privatekey_file_ext}
```suggestion
privatekey_file_ext=${PRIVATEKEY_FILE_EXT:-.pem}
privatekey_file=${privatekey_file_name}${privatekey_file_ext}
```

We have to remove white spaces, as otherwise the variables are interpreted as commands.

2022-04-26 12:53 UTC, kereis commented on README.md
> +| `PRIVATEKEY_FILE_EXT` | `.pem` | `<extension>` | The file extension of the generated private keys.
Thanks for providing a table of available environment variables. :)

2022-04-26 12:53 UTC, kereis commented on README.md
> +| `PRIVATEKEY_FILE_NAME` | `key` | `<filename>` | The file extension of the generated private keys.
```suggestion
| `PRIVATEKEY_FILE_NAME` | `key` | `<filename>` | The file name (without extension) of the generated private keys.
```

Typo.

2022-04-26 12:53 UTC, kereis commented on README.md
> +| `PKCS12_PASSWORD` | unset | `<password>` | Password for the combined PKCS12 , see also `COMBINE_PKCS12`.
```suggestion
| `PKCS12_PASSWORD` | unset | `<password>` | Password for the combined PKCS12, see also `COMBINE_PKCS12`.
```

2022-04-26 12:53 UTC, kereis commented on README.md
> +| `COMBINE_PKCS12` | unset | `yes` | If set to `yes` an additional combined PKCS12 file is created.
```suggestion
| `COMBINE_PKCS12` | unset | `yes` | If set to `yes`, an additional combined PKCS12 file is created.
```

2022-04-26 12:53 UTC, kereis commented on README.md
> +| `ACME_FILE_PATH` | `/traefik/acme.json` | `<filepath>` | Full filepath to traefiks certificates storage.
```suggestion
| `ACME_FILE_PATH` | `/traefik/acme.json` | `<filepath>` | Full file path to Traefik's certificates storage.
```

2022-04-26 12:53 UTC, kereis commented on README.md
> +There are some environment variables if you want to customize various things inside the docker container:
```suggestion
There are some environment variables if you want to customize various things inside the Docker container:
```

2022-04-26 12:53 UTC, kereis commented on README.md
> +| `PRIVATEKEY_FILE_EXT` | `.pem` | `<extension>` | The file extension of the generated private keys.
```suggestion
| `PRIVATE_KEY_FILE_NAME` | `key` | `<filename>` | The file extension of the generated private keys.
| `PRIVATE_KEY_FILE_EXT` | `.pem` | `<extension>` | The file extension of the generated private keys.
```

Besides, should we maybe consider adding an underscore between `PRIVATE` and `KEY`? I think this would be better regarding spelling. :)

If we can agree on this, we shouldn't forget to adjust the variable inside `dump.sh` that is set by each environment variable respectively.

2022-04-26 12:53 UTC, kereis commented on README.md
> +- [Help!](#help)
Is this caused by auto-formatting? Which IDE/formatter did you use?

2022-04-26 12:53 UTC, kereis commented on bin/dump.sh
> +    --key-ext ${privatekey_file_ext} \
```suggestion
    --crt-name "${certificate_file_name}" \
    --crt-ext "${certificate_file_ext}" \
    --key-name "${privatekey_file_name}" \
    --key-ext "${privatekey_file_ext}" \
```

Add quotes in order to prevent globbing. See also https://github.com/koalaman/shellcheck/wiki/SC2086.
https://github.com/koalaman/shellcheck/wiki/SC2086

2022-04-26 12:53 UTC, kereis commented on bin/dump.sh
>      --source ${acme_file_path} >/dev/null
```suggestion
    --source "${acme_file_path}" >/dev/null
```

Same applies here as of above.

2022-04-26 12:53 UTC, kereis commented on bin/dump.sh
>      --source ${acme_file_path} >/dev/null
I see that this is recurring problem throughout the script. This should be fixed later on, but we can at least start applying those changes. :)

2022-04-26 22:07 UTC, BobSilent commented on README.md
> +- [Help!](#help)
I use VsCode with [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) and [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).

it showed me that the TOC was outdated, so i simply used the command to auto update the TOC.
shall I revert?

the linter also shows some other hints, which I did not correct right now

2022-04-26 22:08 UTC, BobSilent commented on bin/dump.sh
> +privatekey_file= ${privatekey_file_name}${privatekey_file_ext}
right, stupid mistake. although i am not a bash expert 😉

2022-04-26 22:09 UTC, BobSilent commented on README.md
> +| `PRIVATEKEY_FILE_EXT` | `.pem` | `<extension>` | The file extension of the generated private keys.
I think the environment configuration has grown to a number where this gets really helpful 😁

2022-04-26 22:10 UTC, BobSilent commented on bin/dump.sh
> +    --key-ext ${privatekey_file_ext} \
Thanks for the hint, as I am not a bash expert

2022-04-26 22:17 UTC, BobSilent commented on bin/dump.sh
> +    --key-ext ${privatekey_file_ext} \
...and just added https://github.com/timonwong/vscode-shellcheck to VsCode 😉

2022-04-27 21:05 UTC, BobSilent commented on README.md
> +- [Help!](#help)
with every save the toc got recreated, i now fixed it.

If these are too many changes just tell me and I will revert.

2022-04-30 10:02 UTC, kereis commented on README.md
> +- [Help!](#help)
> it showed me that the TOC was outdated, so i simply used the command to auto update the TOC. shall I revert?

Updating the ToC is fine. I just wondered because I used asterisks instead of dashes when listing the chapters and actually it shouldn't make a big difference. I hope that this won't become an issue later on.

> the linter also shows some other hints, which I did not correct right now

I think this does not have high priority right now, as for example, I was thinking about moving the whole information to separate pages; either GitHub Wiki or use e. g. Read The Docs.

2022-04-30 11:52 UTC, BobSilent commented on README.md
> +- [Help!](#help)
Sounds good, so I keep the changes as is right now?!

2022-04-30 11:52 UTC, BobSilent commented
Anything else I should update?
just let me know.

2022-05-01 16:46 UTC, kereis commented
I think this should work fine. I tested it quickly yesterday again, and it seems to still work. 😄 

Thanks for your contribution!

2022-05-01 16:46 UTC, merged