Added RSA key file support
kereis/traefik-certs-dumper pull request #82
Opened 2022-04-14 10:03 UTC by ggruening

Hello everybody,

some applications (like `mysql` for example) need key files in RSA format. I prepared RSA key conversion using openssl. You can enable it by setting `CONVERT_KEY2RSA=yes`. 
If you think this is useful I'd update the README, too.

Best regards, and thanks for this fantastic tool.

Gregor

2022-04-26 13:48 UTC, kereis commented
Hey, thank you for your contribution.

I have 2 suggestions:
1. Renaming `CONVERT_KEY2RSA` to `CONVERT_KEY_TO_RSA`.
2. As the new flag will affect all keys involved in the extraction process, we should consider renaming it into `CONVERT_KEYS_TO_RSA` (with `KEYS` having a plural 's')

2022-04-26 17:09 UTC, ggruening commented
I gladly took up your suggestions, see my second commit.

2022-05-01 16:54 UTC, kereis requested changes
Thank you for applying the suggestions. 👍 

Another change that I have to request: #78 was merged recently which introduces a new way of specifying file names and extensions for both certificate and private key file. So you may adjust `convert_keys_to_rsa()` accordingly. See my review comments.

2022-05-01 16:54 UTC, kereis commented on bin/dump.sh
> +      if [[ -f ${outputdir}/${i}/cert.pem && -f ${outputdir}/${i}/key.pem ]]; then
```suggestion
      if [[ -f "${outputdir}/${i}/${certificate_file}" && -f "${outputdir}/${i}/${privatekey_file}" ]]; then
```

As of #78, you have to use `${privatekey_file}` and `${certificate_file}` respectively for `cert.pem` and `key.pem`.

2022-05-01 16:54 UTC, kereis commented on bin/dump.sh
> +    if [[ -f ${outputdir}/cert.pem && -f ${outputdir}/key.pem ]]; then
```suggestion
    if [[ -f "${outputdir}/${certificate_file}" && -f "${outputdir}/${privatekey_file}" ]]; then
```

See previous review comment regarding #78.

2022-05-01 16:54 UTC, kereis commented on bin/dump.sh
> +        openssl rsa -in ${outputdir}/"${i}"/key.pem -out ${outputdir}/"${i}"/rsakey.pem
```suggestion
        openssl rsa -in "${outputdir}/${i}/${privatekey_file}" -out "${outputdir}/${i}/rsakey.pem"
```

See also previous comment. For consistency, maybe we should also introduce an environment variable for settings file name + extension of `rsakey.pem`? See https://github.com/kereis/traefik-certs-dumper/commit/cea5907733267e935a8d0b10145d672589fc30d1#diff-ed933e4c63bca6ca162f9af2745864cfea768a052ed1dd83c00f04b3b4b878e3R8 for reference.

2022-05-03 09:39 UTC, ggruening commented on bin/dump.sh
> +        openssl rsa -in ${outputdir}/"${i}"/key.pem -out ${outputdir}/"${i}"/rsakey.pem
I am happy to take care of your suggestions concerning a new environment variable for `rsakey.pem`. I'll hope I will find the time during the next days.

2022-05-03 14:55 UTC, ggruening commented
Hey ho, I did it similar to https://github.com/kereis/traefik-certs-dumper/pull/78, should be consistent again.

2022-05-04 14:42 UTC, kereis requested changes
Thanks.

One tiny thing though: Can you add your new environment variables to the table of README.md? Afterwards, we can go ahead and merge your changes.

2022-05-04 19:26 UTC, ggruening commented
I just added the new vars to the table of README.md. Furthermore I added an usage example. Hope this helps.

2022-05-05 20:24 UTC, kereis approved these changes
LGTM.

I will merge this one. Thank you for your contribution. 😄 👍

2022-05-05 20:24 UTC, merged

2022-05-06 04:48 UTC, ggruening commented
You're welcome. Thanks again for your work. :)