Avoid flooded log files
kereis/traefik-certs-dumper pull request #91
Opened 2022-05-13 13:35 UTC by ggruening

This fixes issue https://github.com/kereis/traefik-certs-dumper/issues/90

2022-05-17 21:49 UTC, kereis requested changes
Hi,

Thanks again for your contribution! 👍 
I left some review comments. :)

Cheers

2022-05-17 21:49 UTC, kereis commented on bin/dump.sh
> +    sleep 10
Should we maybe make this configurable via environment variables?

2022-05-17 21:49 UTC, kereis commented on bin/dump.sh
> +  if [[ -f ${acme_file_path} ]]; then
If `${acme_file_path}` is not a file, we leave it as it is completely silent. Shouldn't we `exit 1` if that's the case?

2022-05-18 12:53 UTC, ggruening commented on bin/dump.sh
> +  if [[ -f ${acme_file_path} ]]; then
For me, that's a _design decision_ I can't really make. If we do it as you suggested, we end the container. This is also likely to happen completely silently. E.g. someone would reconfigure the `traefik` container and temporarily rename the output file, our container would die. 
In my suggestion, it survives and waits for a proper file. I wanted to keep the status that has been followed so far. 
I don't know which is better. What's your opinion? I'm afraid it's up to you as the author to decide. :-)

2022-05-18 12:59 UTC, ggruening commented on bin/dump.sh
> +    sleep 10
We can do that, even if I don't think there are many users who want to adjust something here... But a variable is not a problem. Is `$retry_interval` a good name for it? Or do we need it more specific?

2022-05-18 13:51 UTC, ggruening commented
@kereis , I commented your review comments. ;) There are two decisions left for me.

2022-05-24 07:17 UTC, kereis commented on bin/dump.sh
> +    sleep 10
Hm, I guess if someone needs that feature, then they should simply create an issue/PR.

2022-05-24 07:21 UTC, kereis commented on bin/dump.sh
> +  if [[ -f ${acme_file_path} ]]; then
I haven't really thought about this one and to be honest, I don't know what would be best practice. Maybe we leave it as it is for now.

2022-05-25 20:54 UTC, kereis requested changes
Got one more suggestion before merging. :)

2022-05-30 19:55 UTC, kereis approved these changes
LGTM. Thanks again. :)

2022-05-30 19:55 UTC, merged